[language-server.pylsp.config.plugins]
pyflakes = {enabled = false}
mccabe = {enabled = false}
pycodestyle = {enabled = false}
yapf = {enabled = false}
autopep8 = {enabled = false}
black = {enabled = true}
rope_autoimport = {enabled = true}
ruff = {enabled = true}

[[language]]
name = "python"
auto-format = true
language-servers = [ "pylsp" ]

[language-server.denols]
command = "deno"
args = ["lsp"]
config = { enable = true, suggest = { imports = { hosts = {"https://deno.land" = true}}}}

[[language]]
name = "typescript"
language-servers = ["denols"]

