[language-server.pylsp.config.plugins]
pyflakes = {enabled = false}
mccabe = {enabled = false}
pycodestyle = {enabled = false}
yapf = {enabled = false}
autopep8 = {enabled = false}
black = {enabled = true}
rope_autoimport = {enabled = true}
ruff = {enabled = true}

[language-server.angularls]
command = "ngserver"
args = ["--stdio", "--tsProbeLocations", "/home/axel/.local/share/npm/lib/node_modules", "--ngProbeLocations", "/home/axel/.local/share/npm/lib/node_modules"]

[language-server.tsserver]
command = "tsserver"
args = ["--stdio"]
config.hostInfo = "helix"

[[language]]
name = "python"
auto-format = true
language-servers = [ "pylsp" ]

[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "angular"] }
language-servers = ["angularls", "tailwindcss-ls", "vscode-html-language-server"]

[[language]]
name = "css"
formatter = { command = 'prettier', args = ["--parser", "css"] }
language-servers = [ "vscode-css-language-server" ]

[[language]]
name = "typescript"
formatter = { command = 'prettier', args = ["--parser", "angular"] }
language-servers = [ "angularls", "tsserver" ]

