# What modes are supported ?
# cat /sys/power/mem_sleep
# s2idle [deep]
# s2idle and sleep are both supported.

# Drop this configuration at this location :
# /etc/systemd/sleep.conf.d/deep-sleep.conf
# It will enable suspend to memory or deep-sleep instead of s2idle.

[Sleep]
MemorySleepMode=deep
