exec spectrwm & 
setxkbmap fr &
xrdb -merge ~/.config/X11/Xresources & 
xautolock -time 10 -locker slock -corners ---- &
compton -b --config .config/compton/compton.sample.conf &
dunst -conf ~/.config/dunst/dunstr
