xautolock -time 10 -locker slock -corners ---- &
xwallpaper --zoom ~/pics/noah-silliman-01Qqkfz-ck8-unsplash.jpg &
dunst -conf ~/.config/dunst/dunstrc &
compton -b --config ~/.config/compton/compton.sample.conf &
slstatus &
xrdb -merge ~/.config/X11/Xresources & 
#sxhkd &
#ssh-agent berry 
dwm
