context.modules = [
	{   name = libpipewire-module-loopback
		args = {
			audio.position = [ FL FR ]
			capture.props = {
				media.class = Audio/Sink
				node.name = game_sink
				node.description = "Virtual game sink"
			}
		}
	}
	{   name = libpipewire-module-loopback
		args = {
			audio.position = [ FL FR ]
			capture.props = {
				media.class = Audio/Sink
				node.name = live_only_sink
				node.description = "Live-only virtual sink"
			}
		}
	}
]